services:
  # Main Flask application
  web:
    build: .
    ports:
      - "8088:8088"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=false
      - SECRET_KEY=docker-dev-secret-key-change-in-production
      # SQLite configuration (default)
      - USE_SQLITE=true
      - DATABASE_URL=
      - HOST=0.0.0.0
      - PORT=8088
      # Firebase configuration (update with your values)
      - FIREBASE_API_KEY=${FIREBASE_API_KEY:-AIzaSyCWIvA2I6kzqokVpq5gjGlMj03Gp3Hwe3E}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN:-dmr-fns.firebaseapp.com}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-dmr-fns}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-dmr-fns.firebasestorage.app}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID:-668810466125}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID:-1:668810466125:web:aeb977be6046bc45d3dd04}
      - FIREBASE_VAPID_KEY=${FIREBASE_VAPID_KEY:-BMQhfotmIce_250TfjNABeg-l_OPWwe2ghk_BwKL0pmyPVVyEsCiaAHniErBw8pw7RJnMp9kD5oU3DDG1Tlod2k}
      - FIREBASE_KEY_PATH=firebase-key.json
    env_file:
      - .env
    volumes:
      # Mount source code for development (comment out for production)
      - .:/app
      # Mount persistent storage for data and backups
      - app_data:/app/data
      - app_backups:/app/data/backups
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - ranch_network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --save 60 1000
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - ranch_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - ranch_network
    profiles:
      - production

volumes:
  redis_data:
    driver: local
  app_data:
    driver: local
  app_backups:
    driver: local

networks:
  ranch_network:
    driver: bridge
